package com.forgeStackk.EduResolve.controller;

import org.springframework.web.bind.annotation.*;

import java.util.Arrays;
import java.util.List;

@RestController
@RequestMapping("/api/schools")
@CrossOrigin(origins = "*")
public class SchoolController {

    /**
     * Get list of schools in Uttar Pradesh
     * GET /api/schools
     */
    @GetMapping
    public List<String> getUttarPradeshSchools() {
        return Arrays.asList(
            "Delhi Public School, Lucknow",
            "City Montessori School, Lucknow",
            "La Martiniere College, Lucknow",
            "St. Francis' College, Lucknow",
            "Loreto Convent, Lucknow",
            "Seth M.R. Jaipuria School, Lucknow",
            "Amity International School, Lucknow",
            "Modern School, Lucknow",
            "Springdale College, Lucknow",
            "St. Anthony's College, Lucknow",
            "Christ Church College, Lucknow",
            "National P.G. College, Lucknow",
            "Kendriya Vidyalaya, Lucknow",
            "Army Public School, Lucknow",
            "Bal Vidya Mandir, Lucknow",
            "Hindustan College, Lucknow",
            "Isabella Thoburn College, Lucknow",
            "Avadh College, Lucknow",
            "Karamat Hussain Muslim College, Lucknow",
            "Lucknow Christian College, Lucknow",
            "D.A.V. College, Lucknow",
            "St. Mary's College, Lucknow",
            "Unity College, Lucknow",
            "Shivaji College, Lucknow",
            "Navyug Kanya Vidyalaya, Lucknow",
            "S.N. Sen Girls' College, Lucknow",
            "Queen's College, Lucknow",
            "Arya Kanya Degree College, Lucknow",
            "B.N. College, Lucknow",
            "J.N. Medical College, Lucknow",
            "King George's Medical University, Lucknow",
            "Dr. Ram Manohar Lohia Institute of Medical Sciences, Lucknow",
            "Babu Banarasi Das University, Lucknow",
            "University of Lucknow, Lucknow",
            "Ambedkar University, Lucknow",
            "Integral University, Lucknow",
            "Lucknow University, Lucknow",
            "Sarojini Naidu Medical College, Agra",
            "Dayalbagh Educational Institute, Agra",
            "St. John's College, Agra",
            "Agra College, Agra",
            "RBS College, Agra",
            "Bhindar College, Agra",
            "Kanpur University, Kanpur",
            "Harcourt Butler Technical University, Kanpur",
            "GSVM Medical College, Kanpur",
            "Christ Church College, Kanpur",
            "D.A.V. College, Kanpur",
            "P.P.N. College, Kanpur",
            "Halat College, Kanpur",
            "V.S.S.D. College, Kanpur",
            "National P.G. College, Kanpur",
            "Juhari Devi College, Kanpur",
            "Chandra Shekhar Azad University of Agriculture & Technology, Kanpur",
            "Indian Institute of Technology, Kanpur",
            "Motilal Nehru National Institute of Technology, Allahabad",
            "University of Allahabad, Allahabad",
            "Allahabad University, Allahabad",
            "Ewing Christian College, Allahabad",
            "Sam Higginbottom University of Agriculture, Technology and Sciences, Allahabad",
            "United College of Engineering & Research, Allahabad",
            "B.B.D. University, Lucknow",
            "M.J.P. Rohilkhand University, Bareilly",
            "Mahatma Jyotiba Phule Rohilkhand University, Bareilly",
            "Rohilkhand University, Bareilly",
            "Bareilly College, Bareilly",
            "M.J.P. Rohilkhand University, Bareilly",
            "S.V. College, Bijnor",
            "Kumaun University, Nainital",
            "D.S.B. College, Nainital",
            "Kumaun University, Nainital",
            "G.B. Pant University of Agriculture & Technology, Pantnagar",
            "Govind Ballabh Pant University of Agriculture & Technology, Pantnagar",
            "Sardar Bhagat Singh College, Varanasi",
            "Banaras Hindu University, Varanasi",
            "Mahatma Gandhi Kashi Vidyapith, Varanasi",
            "Uttar Pradesh Rajarshi Tandon Open University, Allahabad",
            "Dr. A.P.J. Abdul Kalam Technical University, Lucknow",
            "Uttar Pradesh Technical University, Lucknow",
            "Madan Mohan Malaviya University of Technology, Gorakhpur",
            "Deen Dayal Upadhyay Gorakhpur University, Gorakhpur",
            "Gorakhpur University, Gorakhpur",
            "St. Andrew's College, Gorakhpur",
            "Gorakhpur University, Gorakhpur",
            "M.J.P. Rohilkhand University, Bareilly",
            "Bareilly College, Bareilly",
            "Rohilkhand University, Bareilly",
            "S.V. College, Bijnor",
            "Kumaun University, Nainital",
            "D.S.B. College, Nainital",
            "Kumaun University, Nainital",
            "G.B. Pant University of Agriculture & Technology, Pantnagar",
            "Govind Ballabh Pant University of Agriculture & Technology, Pantnagar",
            "Sardar Bhagat Singh College, Varanasi",
            "Banaras Hindu University, Varanasi",
            "Mahatma Gandhi Kashi Vidyapith, Varanasi",
            "Uttar Pradesh Rajarshi Tandon Open University, Allahabad",
            "Dr. A.P.J. Abdul Kalam Technical University, Lucknow",
            "Uttar Pradesh Technical University, Lucknow",
            "Madan Mohan Malaviya University of Technology, Gorakhpur",
            "Deen Dayal Upadhyay Gorakhpur University, Gorakhpur",
            "Gorakhpur University, Gorakhpur",
            "St. Andrew's College, Gorakhpur",
            "Gorakhpur University, Gorakhpur"
        );
    }
}
