package com.forgeStackk.EduResolve.service.student;

import com.forgeStackk.EduResolve.dto.student.StudentInboxItemDto;
import com.forgeStackk.EduResolve.entity.Subject;
import com.forgeStackk.EduResolve.entity.teacher.*;
import com.forgeStackk.EduResolve.enums.*;
import com.forgeStackk.EduResolve.repository.SubjectRepository;
import com.forgeStackk.EduResolve.repository.teacher.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.mockito.junit.jupiter.MockitoSettings;
import org.mockito.quality.Strictness;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.test.util.ReflectionTestUtils;
import org.springframework.web.server.ResponseStatusException;

import java.time.Instant;
import java.time.LocalDate;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
@MockitoSettings(strictness = Strictness.LENIENT)
class StudentPortalServiceTest {

    @Mock StudentInboxRepository studentInboxRepo;
    @Mock MessageRepository messageRepo;
    @Mock MessageAttachmentRepository attachmentRepo;
    @Mock AttendanceRepository attendanceRepo;
    @Mock TeacherRepository teacherRepo;
    @Mock SubjectRepository subjectRepo;

    @InjectMocks StudentPortalService service;

    private final UUID STUDENT_ID = UUID.randomUUID();

    // ── helpers ───────────────────────────────────────────────────────────────

    private StudentInbox inbox(UUID msgId) {
        StudentInbox si = new StudentInbox();
        si.setInboxId(UUID.randomUUID());
        si.setStudentId(STUDENT_ID);
        si.setMessageId(msgId);
        si.setReadStatus(InboxReadStatus.UNREAD);
        return si;
    }

    private Message classNoticeMsg(UUID id, UUID senderId) {
        Message m = new Message();
        m.setMessageId(id);
        m.setSenderId(senderId);
        m.setContentType(MessageContentType.TEXT);
        m.setTextBody("Announcement");
        m.setRecipientType(RecipientType.CLASS);
        m.setSentAt(Instant.now());
        m.setIsHomework(false);
        return m;
    }

    private Message homeworkMsg(UUID id, UUID senderId) {
        Message m = classNoticeMsg(id, senderId);
        m.setIsHomework(true);
        m.setTargetSubjectId(10L);
        return m;
    }

    private Teacher teacher(UUID id, String name) {
        Teacher t = new Teacher();
        t.setTeacherId(id);
        t.setFullName(name);
        return t;
    }

    private Subject subject(Long id, String name) {
        Subject s = new Subject();
        ReflectionTestUtils.setField(s, "id", id);  // @Id field generated by DB — use reflection
        s.setName(name);
        return s;
    }

    // ── getInbox ──────────────────────────────────────────────────────────────

    @Test
    void getInbox_emptyInbox_returnsEmptyList() {
        when(studentInboxRepo.findByStudentIdOrderByReceivedAtDesc(eq(STUDENT_ID), any()))
                .thenReturn(new PageImpl<>(List.of()));

        List<StudentInboxItemDto> result = service.getInbox(STUDENT_ID, null, 0, 50);

        assertThat(result).isEmpty();
        verifyNoInteractions(messageRepo);
    }

    @Test
    void getInbox_classNotice_mapsFieldsCorrectly() {
        UUID msgId = UUID.randomUUID();
        UUID senderId = UUID.randomUUID();
        StudentInbox si = inbox(msgId);
        Message msg = classNoticeMsg(msgId, senderId);

        when(studentInboxRepo.findByStudentIdOrderByReceivedAtDesc(eq(STUDENT_ID), any()))
                .thenReturn(new PageImpl<>(List.of(si)));
        when(messageRepo.findAllById(List.of(msgId))).thenReturn(List.of(msg));
        when(teacherRepo.findAllById(anyCollection())).thenReturn(List.of(teacher(senderId, "Ms. Priya")));
        when(subjectRepo.findAllById(anyCollection())).thenReturn(List.of());
        when(attachmentRepo.findByMessageId(msgId)).thenReturn(List.of());

        List<StudentInboxItemDto> result = service.getInbox(STUDENT_ID, null, 0, 50);

        assertThat(result).hasSize(1);
        StudentInboxItemDto dto = result.get(0);
        assertThat(dto.textBody()).isEqualTo("Announcement");
        assertThat(dto.senderName()).isEqualTo("Ms. Priya");
        assertThat(dto.category()).isEqualTo(MessageCategory.CLASS_NOTICE);
        assertThat(dto.readStatus()).isEqualTo("UNREAD");
        assertThat(dto.attachments()).isEmpty();
    }

    @Test
    void getInbox_homeworkMessage_derivesHomeworkCategory() {
        UUID msgId = UUID.randomUUID();
        UUID senderId = UUID.randomUUID();
        StudentInbox si = inbox(msgId);
        Message msg = homeworkMsg(msgId, senderId);

        when(studentInboxRepo.findByStudentIdOrderByReceivedAtDesc(eq(STUDENT_ID), any()))
                .thenReturn(new PageImpl<>(List.of(si)));
        when(messageRepo.findAllById(anyCollection())).thenReturn(List.of(msg));
        when(teacherRepo.findAllById(anyCollection())).thenReturn(List.of(teacher(senderId, "Mr. Kumar")));
        when(subjectRepo.findAllById(anyCollection())).thenReturn(List.of(subject(10L, "Math")));
        when(attachmentRepo.findByMessageId(msgId)).thenReturn(List.of());

        List<StudentInboxItemDto> result = service.getInbox(STUDENT_ID, null, 0, 50);

        assertThat(result).hasSize(1);
        assertThat(result.get(0).category()).isEqualTo(MessageCategory.HOMEWORK);
        assertThat(result.get(0).subjectName()).isEqualTo("Math");
    }

    @Test
    void getInbox_filtersByCategory_excludesNonMatching() {
        UUID msgId = UUID.randomUUID();
        UUID senderId = UUID.randomUUID();
        StudentInbox si = inbox(msgId);
        Message classNotice = classNoticeMsg(msgId, senderId);

        when(studentInboxRepo.findByStudentIdOrderByReceivedAtDesc(eq(STUDENT_ID), any()))
                .thenReturn(new PageImpl<>(List.of(si)));
        when(messageRepo.findAllById(anyCollection())).thenReturn(List.of(classNotice));
        when(teacherRepo.findAllById(anyCollection())).thenReturn(List.of(teacher(senderId, "X")));
        when(subjectRepo.findAllById(anyCollection())).thenReturn(List.of());
        when(attachmentRepo.findByMessageId(any())).thenReturn(List.of());

        // Filter for HOMEWORK — classNotice should be excluded
        List<StudentInboxItemDto> result = service.getInbox(STUDENT_ID, MessageCategory.HOMEWORK, 0, 50);

        assertThat(result).isEmpty();
    }

    @Test
    void getInbox_orphanedInboxEntry_skipped() {
        UUID msgId = UUID.randomUUID();
        StudentInbox si = inbox(msgId);

        when(studentInboxRepo.findByStudentIdOrderByReceivedAtDesc(eq(STUDENT_ID), any()))
                .thenReturn(new PageImpl<>(List.of(si)));
        when(messageRepo.findAllById(anyCollection())).thenReturn(List.of()); // message deleted

        List<StudentInboxItemDto> result = service.getInbox(STUDENT_ID, null, 0, 50);

        assertThat(result).isEmpty();
    }

    @Test
    void getInbox_messageWithAttachments_mapsAttachmentInfo() {
        UUID msgId = UUID.randomUUID();
        UUID senderId = UUID.randomUUID();
        StudentInbox si = inbox(msgId);
        Message msg = classNoticeMsg(msgId, senderId);

        MessageAttachment att = new MessageAttachment();
        att.setAttachmentId(UUID.randomUUID());
        att.setFileType(AttachmentFileType.DOCUMENT);
        att.setFileName("notes.pdf");
        att.setFileSizeBytes(1024L);
        att.setMimeType("application/pdf");

        when(studentInboxRepo.findByStudentIdOrderByReceivedAtDesc(eq(STUDENT_ID), any()))
                .thenReturn(new PageImpl<>(List.of(si)));
        when(messageRepo.findAllById(anyCollection())).thenReturn(List.of(msg));
        when(teacherRepo.findAllById(anyCollection())).thenReturn(List.of(teacher(senderId, "Ms. Priya")));
        when(subjectRepo.findAllById(anyCollection())).thenReturn(List.of());
        when(attachmentRepo.findByMessageId(msgId)).thenReturn(List.of(att));

        List<StudentInboxItemDto> result = service.getInbox(STUDENT_ID, null, 0, 50);

        assertThat(result.get(0).attachments()).hasSize(1);
        assertThat(result.get(0).attachments().get(0).fileType()).isEqualTo("DOCUMENT");
        assertThat(result.get(0).attachments().get(0).fileName()).isEqualTo("notes.pdf");
    }

    // ── markRead ──────────────────────────────────────────────────────────────

    @Test
    void markRead_setsReadStatusToRead() {
        UUID inboxId = UUID.randomUUID();
        StudentInbox si = new StudentInbox();
        si.setInboxId(inboxId);
        si.setStudentId(STUDENT_ID);
        si.setReadStatus(InboxReadStatus.UNREAD);

        when(studentInboxRepo.findById(inboxId)).thenReturn(Optional.of(si));
        when(studentInboxRepo.save(any())).thenAnswer(inv -> inv.getArgument(0));

        service.markRead(STUDENT_ID, inboxId);

        verify(studentInboxRepo).save(argThat(row ->
                row.getReadStatus() == InboxReadStatus.READ));
    }

    @Test
    void markRead_inboxNotFound_throwsNotFound() {
        UUID inboxId = UUID.randomUUID();
        when(studentInboxRepo.findById(inboxId)).thenReturn(Optional.empty());

        assertThatThrownBy(() -> service.markRead(STUDENT_ID, inboxId))
                .isInstanceOf(ResponseStatusException.class)
                .hasMessageContaining("not found");
    }

    @Test
    void markRead_wrongStudent_throwsForbidden() {
        UUID inboxId = UUID.randomUUID();
        StudentInbox si = new StudentInbox();
        si.setInboxId(inboxId);
        si.setStudentId(UUID.randomUUID()); // different student
        si.setReadStatus(InboxReadStatus.UNREAD);

        when(studentInboxRepo.findById(inboxId)).thenReturn(Optional.of(si));

        assertThatThrownBy(() -> service.markRead(STUDENT_ID, inboxId))
                .isInstanceOf(ResponseStatusException.class)
                .hasMessageContaining("denied");
    }

    // ── getUnreadCount ────────────────────────────────────────────────────────

    @Test
    void getUnreadCount_delegatesToRepository() {
        when(studentInboxRepo.countByStudentIdAndReadStatus(STUDENT_ID, InboxReadStatus.UNREAD))
                .thenReturn(5L);

        assertThat(service.getUnreadCount(STUDENT_ID)).isEqualTo(5L);
    }

    // ── getAttendance ─────────────────────────────────────────────────────────

    @Test
    void getAttendance_returnsSortedByDate() {
        Attendance a1 = attendance(LocalDate.of(2025, 5, 3), AttendanceStatus.PRESENT);
        Attendance a2 = attendance(LocalDate.of(2025, 5, 1), AttendanceStatus.ABSENT);

        when(attendanceRepo.findByStudentIdAndDateBetween(eq(STUDENT_ID), any(), any()))
                .thenReturn(List.of(a1, a2));

        var result = service.getAttendance(STUDENT_ID, 5, 2025);

        assertThat(result).hasSize(2);
        assertThat(result.get(0).date()).isEqualTo(LocalDate.of(2025, 5, 1));
        assertThat(result.get(1).date()).isEqualTo(LocalDate.of(2025, 5, 3));
    }

    @Test
    void getAttendance_empty_returnsEmptyList() {
        when(attendanceRepo.findByStudentIdAndDateBetween(eq(STUDENT_ID), any(), any()))
                .thenReturn(List.of());

        assertThat(service.getAttendance(STUDENT_ID, 6, 2025)).isEmpty();
    }

    private Attendance attendance(LocalDate date, AttendanceStatus status) {
        Attendance a = new Attendance();
        a.setStudentId(STUDENT_ID);
        a.setClassId("9A");
        a.setDate(date);
        a.setStatus(status);
        a.setMarkedBy(UUID.randomUUID());
        return a;
    }
}
