ALTER TABLE broadcast
    ADD COLUMN IF NOT EXISTS class_id        UUID,
    ADD COLUMN IF NOT EXISTS target_students BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS target_parents  BOOLEAN NOT NULL DEFAULT FALSE;
